In [146]:
import pandas as pd
import matplotlib.pylab as plt
import numpy as np

**Dataset**

In [147]:
data=pd.read_csv('weather.nominal.csv')

In [148]:
#data.columns=['outlook','temperature','humidity','windy','play']

In [149]:
data

     outlook temperature humidity  windy play
0      sunny         hot     high   True   no
1   overcast         hot     high  False  yes
2      rainy        mild     high  False  yes
3      rainy        cool   normal  False  yes
4      rainy        cool   normal   True   no
5   overcast        cool   normal   True  yes
6      sunny        mild     high  False   no
7      sunny        cool   normal  False  yes
8      rainy        mild   normal  False  yes
9      sunny        mild   normal   True  yes
10  overcast        mild     high   True  yes
11  overcast         hot   normal  False  yes
12     rainy        mild     high   True   no

**Support**

In [150]:

def support(transactions , min_support):
  itemset=set([item for sublist in transactions for item in sublist])
  count_items={}
  for item in itemset :
    count=0
    for transaction in transactions :
      set_t=set(transaction)
      if item in transaction :
        count+=1
        
    support = count/len(transactions)
    #filter items that have support > min_support
    
    if min_support <= support and support!=1:
      count_items[item]=support
  count_items=pd.DataFrame.from_dict(count_items,orient='index')
  return count_items

In [151]:
print(support(data.to_numpy(),0.5))

               0
False   0.538462
normal  0.538462
yes     0.692308

In [152]:
import itertools

def create_itemsets(items,k):
  # items=support.index
  perm_set = itertools.combinations(items,k)
  return set(perm_set)

In [153]:
def support_itemsets(transactions , itemsets , min_support):
  count_items={}
  for item in itemsets :
    count=0
    i_set=set(item)
    for transaction in transactions :
      t_set=set(transaction)
      if t_set.intersection(i_set)==i_set :
        count+=1
    support = count/len(transactions)
    #filter items that have support > min_support
    if min_support <= support and support!=1:
       count_items[item]=support
    
  count_items=pd.DataFrame.from_dict(count_items,orient='index')
  return count_items

**Apriori**

In [154]:
def apriori(df,min_support):
  transactions_new = data.copy()
  for c in transactions_new .columns:
      transactions_new[c]=str(c)+"="+transactions_new[c].apply(str)
  transactions=transactions_new.to_numpy()
  item_sep=support(transactions,min_support)
  #min sup >0 a faire
  k=2
  itemset=item_sep.index
  df=pd.DataFrame()
  while len(item_sep)!=0:
    itemsets=create_itemsets(itemset,k)
    item_sep=support_itemsets(transactions,itemsets,min_support)
    print(item_sep,k)

    if not item_sep.empty:
        itemset=list()
        for i in item_sep.index:
         for g in i:
            itemset.append(g)
        itemset=set(itemset)
    k+=1
  
  it=len(itemset)+1
  for i in range(1,it):
    itemsets=create_itemsets(itemset,i)
    item_sep=support_itemsets(transactions,itemsets,min_support)
    df=pd.concat([item_sep,df])
  df=df.reset_index()
  # if all(df.loc[:,0] >= min_support):
  #      df.columns=["itemsets","support"]
  # else:
  #   df.columns = ['support']
  
 
  return df,itemset

In [155]:
dk,Freq_iteam=apriori(data, 0.15)
dk

                                            0
(humidity=high, windy=False)         0.230769
(humidity=normal, outlook=sunny)     0.153846
(windy=True, temperature=mild)       0.230769
(outlook=overcast, temperature=hot)  0.153846
(play=no, outlook=sunny)             0.153846
(temperature=cool, windy=True)       0.153846
(humidity=high, outlook=rainy)       0.153846
(humidity=normal, play=yes)          0.461538
(humidity=normal, windy=False)       0.307692
(play=yes, windy=True)               0.230769
(humidity=normal, windy=True)        0.230769
(play=no, humidity=high)             0.230769
(humidity=high, temperature=mild)    0.307692
(humidity=high, temperature=hot)     0.153846
(play=yes, windy=False)              0.461538
(play=no, windy=True)                0.230769
(humidity=normal, temperature=cool)  0.307692
(humidity=high, outlook=overcast)    0.153846
(play=yes, temperature=cool)         0.230769
(outlook=rainy, windy=True)          0.153846
(play=yes, outlook=rainy)            0.230769
(humidity=normal, outlook=rainy)     0.230769
(outlook=sunny, windy=True)          0.153846
(outlook=rainy, windy=False)         0.230769
(outlook=sunny, windy=False)         0.153846
(windy=False, temperature=hot)       0.153846
(outlook=sunny, temperature=mild)    0.153846
(humidity=high, outlook=sunny)       0.153846
(outlook=rainy, temperature=cool)    0.153846
(play=no, outlook=rainy)             0.153846
(outlook=overcast, windy=True)       0.153846
(windy=False, temperature=cool)      0.153846
(play=yes, temperature=mild)         0.307692
(play=yes, temperature=hot)          0.153846
(humidity=normal, temperature=mild)  0.153846
(outlook=overcast, windy=False)      0.153846
(play=yes, outlook=overcast)         0.307692
(play=no, temperature=mild)          0.153846
(humidity=normal, outlook=overcast)  0.153846
(humidity=high, play=yes)            0.230769
(outlook=rainy, temperature=mild)    0.230769
(humidity=high, windy=True)          0.230769
(windy=False, temperature=mild)      0.230769
(play=yes, outlook=sunny)            0.153846 2
                                                           0
(humidity=normal, temperature=cool, windy=True)     0.153846
(humidity=normal, play=yes, windy=True)             0.153846
(humidity=normal, play=yes, windy=False)            0.307692
(play=no, humidity=high, windy=True)                0.153846
(humidity=normal, play=yes, outlook=rainy)          0.153846
(play=yes, outlook=rainy, temperature=mild)         0.153846
(humidity=high, outlook=rainy, temperature=mild)    0.153846
(play=yes, windy=False, temperature=mild)           0.153846
(humidity=high, windy=False, temperature=mild)      0.153846
(humidity=normal, play=yes, outlook=overcast)       0.153846
(humidity=high, play=yes, windy=False)              0.153846
(outlook=overcast, windy=False, temperature=hot)    0.153846
(play=yes, windy=False, temperature=cool)           0.153846
(outlook=rainy, windy=False, temperature=mild)      0.153846
(humidity=normal, outlook=rainy, windy=False)       0.153846
(play=yes, windy=False, temperature=hot)            0.153846
(humidity=normal, play=yes, outlook=sunny)          0.153846
(play=no, outlook=rainy, windy=True)                0.153846
(play=no, humidity=high, outlook=sunny)             0.153846
(play=yes, outlook=rainy, windy=False)              0.230769
(humidity=normal, play=yes, temperature=cool)       0.230769
(humidity=high, play=yes, outlook=overcast)         0.153846
(play=yes, windy=True, temperature=mild)            0.153846
(humidity=normal, play=yes, temperature=mild)       0.153846
(play=yes, outlook=overcast, temperature=hot)       0.153846
(humidity=normal, windy=False, temperature=cool)    0.153846
(play=no, humidity=high, temperature=mild)          0.153846
(humidity=high, play=yes, temperature=mild)         0.153846
(play=yes, outlook=overcast, windy=True)            0.153846
(play=yes, outlook=overcast, windy=False)           0.153846
(humidity=normal, outlook=rainy, temperature=cool)  0.153846
(humidity=high, windy=True, temperature=mild)       0.153846 3
                                                           0
(play=yes, outlook=rainy, windy=False, temperat...  0.153846
(play=yes, outlook=overcast, windy=False, tempe...  0.153846
(humidity=normal, play=yes, outlook=rainy, wind...  0.153846
(humidity=normal, play=yes, windy=False, temper...  0.153846 4
Empty DataFrame
Columns: []
Index: [] 5

                                                index         0
0   (play=yes, outlook=overcast, windy=False, temp...  0.153846
1   (humidity=normal, play=yes, outlook=rainy, win...  0.153846
2   (play=yes, outlook=rainy, windy=False, tempera...  0.153846
3   (humidity=normal, play=yes, windy=False, tempe...  0.153846
4    (outlook=overcast, windy=False, temperature=hot)  0.153846
5              (play=yes, outlook=rainy, windy=False)  0.230769
6            (humidity=normal, play=yes, windy=False)  0.307692
7           (play=yes, windy=False, temperature=cool)  0.153846
8       (humidity=normal, play=yes, temperature=cool)  0.230769
9           (play=yes, outlook=overcast, windy=False)  0.153846
10     (outlook=rainy, windy=False, temperature=mild)  0.153846
11         (humidity=normal, play=yes, outlook=rainy)  0.153846
12      (humidity=normal, outlook=rainy, windy=False)  0.153846
13        (play=yes, outlook=rainy, temperature=mild)  0.153846
14  (humidity=normal, outlook=rainy, temperature=c...  0.153846
15          (play=yes, windy=False, temperature=mild)  0.153846
16           (play=yes, windy=False, temperature=hot)  0.153846
17      (humidity=normal, play=yes, temperature=mild)  0.153846
18      (play=yes, outlook=overcast, temperature=hot)  0.153846
19      (humidity=normal, play=yes, outlook=overcast)  0.153846
20   (humidity=normal, windy=False, temperature=cool)  0.153846
21                (outlook=overcast, temperature=hot)  0.153846
22                        (humidity=normal, play=yes)  0.461538
23                     (humidity=normal, windy=False)  0.307692
24                            (play=yes, windy=False)  0.461538
25                (humidity=normal, temperature=cool)  0.307692
26                       (play=yes, temperature=cool)  0.230769
27                          (play=yes, outlook=rainy)  0.230769
28                   (humidity=normal, outlook=rainy)  0.230769
29                       (outlook=rainy, windy=False)  0.230769
30                  (outlook=rainy, temperature=cool)  0.153846
31                    (windy=False, temperature=cool)  0.153846
32                       (play=yes, temperature=mild)  0.307692
33                        (play=yes, temperature=hot)  0.153846
34                (humidity=normal, temperature=mild)  0.153846
35                    (outlook=overcast, windy=False)  0.153846
36                       (play=yes, outlook=overcast)  0.307692
37                (humidity=normal, outlook=overcast)  0.153846
38                  (outlook=rainy, temperature=mild)  0.230769
39                    (windy=False, temperature=mild)  0.230769
40                     (windy=False, temperature=hot)  0.153846
41                                (temperature=cool,)  0.307692
42                                (temperature=mild,)  0.461538
43                                 (temperature=hot,)  0.230769
44                                 (humidity=normal,)  0.538462
45                                        (play=yes,)  0.692308
46                                   (outlook=rainy,)  0.384615
47                                (outlook=overcast,)  0.307692
48                                     (windy=False,)  0.538462

Association Rules

In [156]:
dk[dk['support']== 'play=yes']['support']

KeyError: 'support'

In [ ]:
support_itemset = dk[dk['support']== ('play=yes,')]['support']
support_itemset

Series([], Name: support, dtype: float64)

In [167]:
def generate_association_rules(frequent_itemsets, min_confidence,metric='confidence'):
    # sort frequent itemsets by descending support
    if(frequent_itemsets.shape[0] > 0):
        frequent_itemsets.columns=["itemsets","support"]
        frequent_itemsets = frequent_itemsets.sort_values('support', ascending=False)
        rules = []
        for i in range(len(frequent_itemsets)):
            # generate all non-empty subsets of itemset
            itemset = tuple(frequent_itemsets.iloc[i]['itemsets'])
            for j in range(1, len(itemset)):
                for subset in itertools.combinations(itemset, j):
                    subset = tuple(subset)
                    # calculate confidence of rule
                    support_itemset = frequent_itemsets[frequent_itemsets['itemsets'] == itemset]['support'].values
                    support_subset = frequent_itemsets[frequent_itemsets['itemsets'] == subset]['support'].values
                    
                    if len(support_subset) == 0:
                        continue
                    confidence = support_itemset / support_subset[0]
                    if confidence >= min_confidence:
                        # add rule to list
                        support_consequent = frequent_itemsets[frequent_itemsets['itemsets'] == tuple(set(itemset) - set(subset))]['support'].values
                        lift = confidence / support_consequent
                        rules.append({
                            'antecedent': subset,
                            'consequent': set(itemset) - set(subset),
                            'support': support_itemset,
                            'confidence': confidence,
                            'lift' : lift
                        })
        # sort rules by descending confidence
        rules = pd.DataFrame(sorted(rules, key=lambda x: x['confidence'], reverse=True))
        return rules
    else:
         print("there is no association rules")

In [169]:
rules= generate_association_rules(dk, 0.9)
rules['lift']

0     [1.4444444444444444]
1     [1.4444444444444444]
2     [1.8571428571428572]
3     [1.8571428571428572]
4     [1.4444444444444444]
5     [1.8571428571428572]
6     [1.8571428571428572]
7     [1.4444444444444444]
8     [1.8571428571428572]
9     [2.5999999999999996]
10    [1.4444444444444444]
11    [2.1666666666666665]
12    [1.4444444444444444]
13    [1.8571428571428572]
14     [4.333333333333333]
15    [1.8571428571428572]
16                  [3.25]
17    [1.8571428571428572]
18    [1.8571428571428572]
19    [1.4444444444444444]
20    [1.4444444444444444]
21    [1.4444444444444444]
22                  [3.25]
23    [1.4444444444444444]
24    [1.4444444444444444]
25    [1.8571428571428572]
26    [1.4444444444444444]
27                   [6.5]
28                      []
29    [2.1666666666666665]
30                      []
31     [4.333333333333333]
32    [1.8571428571428572]
33                  [3.25]
34    [1.4444444444444444]
Name: lift, dtype: object

In [ ]:
for i in range(len(rules)):
   rules['lift'][1].values[0]

# Amelioration

In [ ]:

def supportA(transactions):
  itemset=set([item for sublist in transactions for item in sublist])
  count_items={}
  for item in itemset :
    count=0
    for transaction in transactions :
      set_t=set(transaction)
      if item in transaction :
        count+=1
        
    support = count/len(transactions)
    #filter items that have support > min_support
    count_items[item]=support
  min_support = sum(count_items.values()) / len(count_items)
  count_items=pd.DataFrame.from_dict(count_items,orient='index')
  count_items=count_items[count_items.values > min_support]
  return count_items

In [ ]:
def support_itemsetsA(transactions , itemsets):
    count_items={}
    for item in itemsets :
        count=0
        i_set=set(item)
        for transaction in transactions :
            t_set=set(transaction)
            if t_set.intersection(i_set)==i_set :
                count+=1
        support = count/len(transactions)
        count_items[item]=support
        
            
    min_support = sum(count_items.values()) / len(count_items)
    count_items=pd.DataFrame.from_dict(count_items,orient='index')
    count_items=count_items[count_items.values > min_support]
    return count_items

In [ ]:
def aprioriA(df):
  transactions_new = data.copy()
  for c in transactions_new .columns:
      transactions_new[c]=str(c)+"="+transactions_new[c].apply(str)
  transactions=transactions_new.to_numpy()
  item_sep=supportA(transactions)
  #min sup >0 a faire
  k=2
  itemset=item_sep.index
  df=pd.DataFrame()
  while len(item_sep)!=0:
    itemsets=create_itemsets(itemset,k)
    item_sep=support_itemsetsA(transactions,itemsets)

    if not item_sep.empty:
        itemset=list()
        for i in item_sep.index:
         for g in i:
            itemset.append(g)
        itemset=set(itemset)
    k+=1
  
  it=len(itemset)+1
  for i in range(1,it):
    itemsets=create_itemsets(itemset,i)
    item_sep=support_itemsetsA(transactions,itemsets)
    df=pd.concat([item_sep,df])
  df=df.reset_index()

 
  return df,itemset

In [ ]:
dkA,freuqnt = aprioriA(data)
dkA

                                   index         0
0   (1=mild, 4=yes;;, 3=FALSE, 2=normal)  0.071429
1     (1=mild, 4=yes;;, 3=FALSE, 2=high)  0.071429
2             (1=mild, 4=yes;;, 3=FALSE)  0.142857
3           (4=yes;;, 3=FALSE, 2=normal)  0.285714
4              (1=mild, 3=FALSE, 2=high)  0.142857
5            (1=mild, 4=yes;;, 2=normal)  0.142857
6             (4=yes;;, 3=FALSE, 2=high)  0.142857
7              (1=mild, 4=yes;;, 2=high)  0.142857
8                     (4=yes;;, 3=FALSE)  0.428571
9                    (3=FALSE, 2=normal)  0.285714
10                   (4=yes;;, 2=normal)  0.428571
11                     (1=mild, 4=yes;;)  0.285714
12                      (1=mild, 2=high)  0.285714
13                            (4=yes;;,)  0.642857

In [ ]:
generate_association_rules(dkA, 0.9)

            antecedent consequent   support  confidence      lift
0  (3=FALSE, 2=normal)  {4=yes;;}  0.285714         1.0  1.555556

# CLOSE

In [ ]:
transactions = [['Milk', 'Onion', 'Nutmeg', 'Kidney Beans' ,'Eggs', 'Yogurt'],
           ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'], 
           ['Milk', 'Apple', 'Kidney Beans', 'Eggs'],
           ['Milk', 'Unicorn', 'Corn', 'Kidney Beans','Yogurt'],
           ['corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice cream', 'Eggs']]

In [ ]:
def support_items(transactions , min_support):
      count_items={}
      itemsets=set([item for sublist in transactions for item in sublist])
      for item in itemsets:
        itemset = frozenset([item])
        support = sum(1 for transaction in transactions if itemset.issubset(transaction)) / len(transactions)
        
        if support >= min_support:
            count_items[itemset] = support
      return  count_items

In [ ]:
def create_itemsets(closed_frequent_itemsets,k):
  itemsets = set(frozenset.union(itemset1, itemset2) for itemset1 in closed_frequent_itemsets for itemset2 in closed_frequent_itemsets if len(itemset1.union(itemset2)) == k)


  return itemsets

In [ ]:
def support_iteamset(transactions,itemsets,min_support):
        frequent_itemsets_k = {}
        taille = len(transactions)
        for itemset in itemsets:
            support = sum(1 for transaction in transactions if itemset.issubset(transaction)) / taille
            if support >= min_support:
                frequent_itemsets_k[itemset] = support
        return frequent_itemsets_k

In [ ]:
def Remove(frequent_itemsets):
   reduced ={}
   for itemset1 in frequent_itemsets:
            redundant = False
            for itemset2 in frequent_itemsets:
                if itemset1 != itemset2 and itemset1.issubset(itemset2) and frequent_itemsets[itemset1] == frequent_itemsets[itemset2]:
                    redundant = True
                    break
            if not redundant:
                reduced[itemset1] = frequent_itemsets[itemset1]
   return reduced

In [ ]:
def close(transactions, min_support):

    
    closed_frequent_itemsets = support_items(transactions , min_support)
  
    k = 2
    while True:
        itemsets = create_itemsets(closed_frequent_itemsets,k)
        if len(itemsets) == 0:
            break
        
        frequent_itemsets = support_iteamset(transactions ,itemsets, min_support)
        if len(frequent_itemsets) == 0:
            break
        
        frequent_itemsets_reduced = Remove(frequent_itemsets)


        closed_frequent_itemsets.update(frequent_itemsets_reduced)
        
        k += 1
    
    return closed_frequent_itemsets

In [ ]:
close(transactions, 0.5)

{frozenset({'Onion'}): 0.6,
 frozenset({'Kidney Beans'}): 1.0,
 frozenset({'Milk'}): 0.6,
 frozenset({'Eggs'}): 0.8,
 frozenset({'Yogurt'}): 0.6,
 frozenset({'Kidney Beans', 'Yogurt'}): 0.6,
 frozenset({'Eggs', 'Onion'}): 0.6,
 frozenset({'Eggs', 'Kidney Beans'}): 0.8,
 frozenset({'Kidney Beans', 'Milk'}): 0.6,
 frozenset({'Kidney Beans', 'Onion'}): 0.6,
 frozenset({'Eggs', 'Kidney Beans', 'Onion'}): 0.6}